package io.eddy08.liv2train.domain;

import java.util.List;
import java.time.Instant;
import lombok.Data;

@Data
public class TrainingCenter {
    private String centerName;
    private String centerCode;
    private Address address;
    private int studentCapacity;
    private List<String> courseOffered;
    
    // Generated By System
    private Instant createdOn;
    
    private String contactEmail;
    private String contactPhone;


}
